apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: ciss
spec:
  selector:
    matchLabels:
      app: ciss
      version: v1
      tier: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: ciss
        version: v1
        tier: frontend
    spec:
      containers:
      - name: ciss
        image: iameprel/ciss:0.0.9
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: DB_HOST
          value: local-mongo-server-ip
        - name: DB_MODE
          value: PRODUCTION
        - name: DB_NAME
          value: ciss
        - name: DB_USER_NAME
          value: test
        - name: DB_PASSWORD
          value: test
        - name: JWT_SECRET
          value: your-jwt-secret
        - name: TWILIO_ACCOUNT_SID
          value: twilio-account-sid
        - name: TWILIO_AUTH_TOKEN
          value: twilio-auth-token
        - name: TWILIO_FROM_NUMBER
          value: twilio-from-number
        ports:
        - containerPort: 3000
